### ISSUE TITLE
[FR]: custom "Key::Value" as trigger to publish

### ISSUE THREAD

**Issue by ArneNostitz** [ObsidianPublisher/obsidian-github-publisher#84]
### Issue validation

- [X] My issue is not a question relative to [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/) nor [Mkdocs](https://www.mkdocs.org/) (*[You can open a discussion to get more help!](https://github.com/squidfunk/mkdocs-material/discussions)*)
- [X] I checked the issue to prevent duplicate

### Workflow

Obsidian plugin 💠

### Is your feature related to a problem ?

I have project related files that are marked with inline "Project:: ProjektName" all over my vault. It would be awesome to have this key-value as custom trigger to be pushed to the git.

thinking ahead a separation by "ProjectName" per Project-Git would be even better

### What solution do you want to see ?

- option to define custom triggers by "key::Value" (not only key)

(option to add multiple git repositories with related key::value)

### OS

MacOS

**Comment by Lisandra-dev** [comment]
For the github repository, I thinked about that when I first developped the fonction, and abandon the idea because it have the exact same limit of the actual fonction, and need more overwork to just create a key/value. The actual behavior is « okay » for me. 

Also, if you have many project connected to different repo, I think it's better to use another vault for that, than the plugin.

For the other suggestion, adding this function necessite a **lot** of rework, as many many function are linked to `if frontmatter[sharekey]`.
If I create this, I need to create another function, that will check the key.... For something I don't see the interest.

If you need to add another key for your repository & the sharing key, you could use linter, metadata-menu, and quickadd. Or, check with VSCode or other IDE to add the key.
Don't forget that to send to another repo, you need to use  
`repo: user/repo/branch` (or just : `repo: repo` if the repo is on your own github)

**Comment by ArneNostitz** [comment]
working in multiple vaults is sub-par in my view as they can not share info. and some of the project related info needs to be shared (contact information for example of people working on multiple projects) or references to previous accomplishements ... 

i get that my "needs" are apparently very unique ... and i am really struggling to get them untangled. :)

there will be a solution - i am sure

thanks for the fast response.

**Comment by Lisandra-dev** [comment]
Hello!
I changed my mind after some times and develop in #add-multiple-repo the possibility to set `shortRepo`, and allowing to set commands & everything to more than one repo!
I know it's not 100% the thing you want, but now you can remove regex & all if you want to use multiple repo!
